### PR TITLE
Update payments query for EDD 3.0 compatibility #65

### LINKED ISSUE #65: Update query_customer_payments() for EDD 3.0 compatibility
This query needs updating to be compatible with EDD 3.0:

https://github.com/webzunft/edd-helpscout/blob/master/includes/class-endpoint.php#L202-L221

Optionally, the contents of `get_customer_orders()` _could_ be updated for improved performance in EDD 3.0: https://github.com/webzunft/edd-helpscout/blob/master/includes/class-endpoint.php#L247-L302 As is, once the actual customer payments query is updated `get_customer_orders()` should work perfectly fine, but there is a performance hit if you work with `EDD_Payment` instead of the new `Order` object in 3.0.

---

I (or someone else from the EDD team) will be happy to work up a PR for this soon, just getting the issue in. :+1:

### PR DESCRIPTION
**Pull request by ashleyfae**
Closes #65 

## Changes

- `query_customer_payments()`
    - Performs a new orders query if on EDD 3.0. If on EDD 2.x then the old query is still run unchanged.
    - In EDD 3.0, the return value of this method is now an array of `EDD\Orders\Order` objects instead of order (payment) IDs. I thought this would be okay as it's a private method.
- `get_customer_orders()`
    - Refactored to support that the result of the query method could be an array of Order objects. There are a few new conditional statements to handle that when formatting the data. Working with Order objects here was an optional move, but it avoids the performance hit that comes from still using `EDD_Payment` objects instead.
- `get_payment_method()`
    - The method has been reworked slightly to support that the parameter could be either an Order object or an EDD_Payment object.
    - Added `manual` to the switch statement along with `manual_purchases`. In EDD 3.0 the manual payments gateway has been merged into core, but the key is just `manual`.

I took a few screenshots to show the data still returns the same.

### `master` branch

helpscout-master

### `issue/65`

helpscout-pr-v2

## EDD 3.0

This is a different customer from the above because the data is coming from another install, but shows everything still fundamentally works.

Note: Order 3 has no product title because it actually was an order with no items.

helpscout-pr-v3-1
helpscout-pr-v3-2

### Upgrade

helpscout-pr-v3-upgrade

---

@robincornett can you look over this before I mark it as ready for review?

### CODE REVIEW

**Comment by flowdee** [comment]
Thanks for providing the code @ashleyfae 👍

**Review by robincornett — APPROVED** [review]
My apologies for coming to this late, but the code all looks logical/reasonable to me.

**Comment by webzunft** [comment]
Thank you, @ashleyfae. I am currently testing and will merge the PR when no issues show up by tomorrow.

**Comment by webzunft** [comment]
Merged after testing on our live site for 24 hours.

**Pull request merged**
