### PR TITLE
Refactor data collection & templating

### PR DESCRIPTION
**Pull request by Spreeuw**
Following previous work on #62 and #59 we have decided to refactor the data structure and output of the plugin. A lot of logic had crept into the `order-row.php` template and the need to display more information (license upgrades, renewal links, subscription information) no longer fit the singular layout.

This PR addresses both the technical debt of several patches that were applied over the years as well as creating a more flexible/readable layout to support different _types_ of data.

The customer data has now been divided into 4 different templates:

## Customer data
When multiple EDD customer profiles are connected to a helpscout customer, these will now all be shown, with links to both the WP user profile and the EDD customer profile, including the name for each profile
Customers

## Licenses (shown only when EDD Software Licensing is used)
Licenses are separated from orders since typically, multiple orders (original orders and renewals) would be connected to the same license information, leading to duplication. Being separated from the order data also gives more space to show both upgrade links (when license upgrades are available) and site activations. Colored badges are used to indicate license status. A renewal link is provided for expired licenses.
Licenses-1 Licenses-2

## Orders
This is very much simplified compared to the current releases, it only shows information relevant primarily to the order: Status, purchased items, payment gateway link and date + time
Orders

## Subscriptions (shown only when EDD Recurring is used)
This information is not available in the current release but helpful for support staff to see the status of subscriptions from the customer
Subscriptions

Feedback is welcome!

### CODE REVIEW

**Comment by flowdee** [comment]
Looks awesome!

**Comment by flowdee** [comment]
@Spreeuw would be great if you could visually highlight an order as "upgrade" in case it was a license upgrade. 

Similar to the "RENEWAL" badge, a "UPGRADE" would be a good fit i guess?

**Comment by Spreeuw** [comment]
@flowdee I've added a "License upgrade" badge to items that were upgraded - note that this is not an order status (like "Renewal" but a per-item property)

**Comment by webzunft** [comment]
Thanks @Spreeuw The badge is a bit too close to the product name. Or is that just caching?

upgrade-batch

**Comment by Spreeuw** [comment]
It's on a new line for me, but maybe that's because I have longer product names. The default HelpScout App styles for list items are a bit messy. Normally I'm a fan of `flexbox` but for this purpose (in `li` elements) I don't think it's very useful. It should actually be below the '2 - 5 sites' in this case. I'll fix that shortly.

**Comment by Spreeuw** [comment]
After discussion with @webzunft we decided to drop the composer autoloader and the tests (which had not been maintained anyway) in favor of a simple autoloader using `spl_autoload_register`, resulting in a much lighter package altogether.

**Comment by webzunft** [comment]
@Spreeuw I ran this version for a week on our production server and it worked without issues. Could I ask you to see if you can resolve the merge conflict so that I can merge it into the master branch?

**Comment by flowdee** [comment]
Seems like you dropped the "Deactivate site" link? At least my support agents told me that they can't remotely deactivate sites anymore

**Comment by Spreeuw** [comment]
@flowdee added back in 2be5878

**Comment by Spreeuw** [comment]
@webzunft I've merged your changes from master to resolve the conflicts

**Comment by flowdee** [comment]
@Spreeuw from my site thanks a lot for your work. The new widgets look wonderful and are really helpful!

**Pull request merged**
